"""fixed all chnages in models-events-seats-venues

Revision ID: d75123bda9c7
Revises: 3abece2192c2
Create Date: 2026-08-26 18:07:15.279153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd75123bda9c7'
down_revision: Union[str, Sequence[str], None] = '3abece2192c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_venue_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'venues', ['venue_id'], ['id'])
    op.alter_column('venues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_venue_id_fkey'), 'events', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
